### ISSUE TITLE
Move from old website

### ISSUE THREAD

**Issue by leejuyuu** [nomacs/nomacs.github.io#1]
The latest archived snapshot I found is https://web.archive.org/web/20230818235517/https://nomacs.org/.
I am planning to move the main page to the new site. For the downloads and releases, I will link to github for now.
I could also attempt to scrape the old release notes but I am unsure whether I should prioritize building a documentation up.
Any thoughts?

**Comment by leejuyuu** [comment]
Due to the SSG nature of the new site, the comments will not be moved.

**Comment by mmahmoudian** [comment]
The old website is still available ( https://nomacs.cvl.tuwien.ac.at/ ) and we don't need to rely on Web Archive.

Comments are useless at this point.

**Comment by leejuyuu** [comment]
Thanks for the link to the old website. Didn't notice that there was a documentation page. I will prioritize porting that.
